spring.application.name=FiguriQA 2026
server.port=8080

spring.datasource.url=jdbc:h2:mem:figuriqa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
server.servlet.session.timeout=45m
