CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    city VARCHAR(255),
    nickname VARCHAR(255)
);

CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    group_name VARCHAR(255) NOT NULL,
    fictional_confederation VARCHAR(255) NOT NULL
);

CREATE TABLE stickers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    rarity VARCHAR(255) NOT NULL,
    team_id BIGINT NOT NULL,
    CONSTRAINT fk_stickers_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE user_stickers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sticker_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_user_stickers_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_stickers_sticker FOREIGN KEY (sticker_id) REFERENCES stickers(id),
    CONSTRAINT uq_user_stickers_user_sticker UNIQUE (user_id, sticker_id)
);

CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    confirmation_code VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT fk_trades_requester FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT fk_trades_receiver FOREIGN KEY (receiver_id) REFERENCES users(id)
);

CREATE TABLE trade_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id BIGINT NOT NULL,
    sticker_id BIGINT NOT NULL,
    direction VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_trade_items_trade FOREIGN KEY (trade_id) REFERENCES trades(id),
    CONSTRAINT fk_trade_items_sticker FOREIGN KEY (sticker_id) REFERENCES stickers(id)
);

CREATE TABLE swap_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_stickers_team ON stickers(team_id);
CREATE INDEX idx_user_stickers_user ON user_stickers(user_id);
CREATE INDEX idx_user_stickers_sticker ON user_stickers(sticker_id);
CREATE INDEX idx_trades_requester ON trades(requester_id);
CREATE INDEX idx_trades_receiver ON trades(receiver_id);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trade_items_trade ON trade_items(trade_id);
CREATE INDEX idx_swap_points_city ON swap_points(city);
